version: '3.8'
services:
  haproxy:
    image: haproxy
    ports:
      - "9000:9000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  goapp1:
    build:
      context: .
      dockerfile: Dockerfile
    image: goapp
    environment:
      - APPPORT=9001
  goapp2:
    image: goapp
    environment:
      - APPPORT=9002
  goapp3:
    image: goapp
    environment:
      - APPPORT=9003